language: node_js
node_js: stable

script: true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: AKIAJ4CL4BCTBOVVEW5Q
    secret_access_key: {AWS_TRAVIS_TOKEN}
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: data.troyyang.com
    on:
      repo:  Troy-Yang/demos
